function [x,c,x_debias,c_debias]=moment_sparsa(y,tau,nsmps)

n = length(y);

[c,c_debias] = SpaRSA(y,@(z) moment_pad(z,nsmps,n),tau/sqrt(nsmps),...
    'AT',@(z) fft(z,nsmps)/sqrt(nsmps),...
    'Psi',@(z,tau) max(real(z)-tau,0).*exp(1i*angle(z)),... %shrinkage function
    'Phi',@(z) sum(z),... %penalty function (l1-norm)
    'MaxiterA',1000,...
    'ToleranceA',1e-12,...
    'Initialization',2,...
    'Verbose',0,...
    'Debias',1);

x = moment_pad(c,nsmps,n);
x_debias = moment_pad(c_debias,nsmps,n);
